apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-gke
  labels:
    app: github-actions-gke
spec:
  selector:
    matchLabels:
      app: github-actions-gke
  replicas: 2
  template:
    metadata:
      labels:
        app: github-actions-gke
    spec:
      containers:
      - name: app
        image: gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        ports:
          - containerPort: 80