
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-gke
  labels:
    app: github-actions-gke
spec:
  selector:
    matchLabels:
      app: github-actions-gke
  replicas: 1
  template:
    metadata:
      labels:
        app: github-actions-gke
    spec:
      containers:
      - name: app
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        ports:
          - containerPort: 80