apiVersion: apps/v1
kind: Deployment

metadata: 
   name: github-actions-gke

spec: 
  replicas: 1
  selector:
    matchLables:
      app: github-actions-gke

template:
  metadata:
    lables: 
      app: github-actions-gke
  spec: 
    containers:
      - name: app
        iamge: gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        imagePullPolicy: Always
