
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-gke
  labels:
    app: github-actions-gke
spec:
  selector:
    matchLabels:
      app: github-actions-gke
  replicas: 2
  template:
    metadata:
      labels:
        app: github-actions-gke
    spec:
      containers:
      - name: app
        image: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GIT_TAG
        ports:
          - containerPort: 80